import "server-only";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { NavBar } from "@/components/nav-bar";
import ShoppingCartProvider from "@/context/shopping-cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ShoppingCartProvider>
            <NavBar />
            {children}
          </ShoppingCartProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
